### PR TITLE
support all unix

### PR DESCRIPTION
**Pull request by oliver-sanders**
~No real change here, just improving consistency with the other repos.~

Rolling the release into this PR.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by datamel — APPROVED** [review]

**Review by MetRonnie — APPROVED** [review]

**Comment by oliver-sanders** [comment]
The auto generated PR never came through so performing this release manually (basically just bump the version number, update the SHA and ensure the bullets in the issue description are fulfilled)

**Comment by oliver-sanders** [comment]
@conda-forge-admin, please rerender

**Review by MetRonnie — APPROVED** [review]
Looks ok to me

**Comment by oliver-sanders** [comment]
Going in with 2 1/2 approvals :/

**Pull request merged**
